# ==============================================================================
# Informations du Projet
# ==============================================================================
site_name: Smart Energy Optimizer
site_url: https://test-orga-2ee5d541-2ef3-4a3f-8bac.github.io/Parent-project/
site_description: Documentation de l'architecture Smart Energy Optimizer
copyright: Copyright &copy; 2026 EnerVision

# ==============================================================================
# Configuration du Dépôt
# ==============================================================================
repo_name: EnerVision
repo_url: https://github.com/enervision-project

# ==============================================================================
# Configuration du Thème (Material)
# ==============================================================================
theme:
  name: material
  language: fr
  logo: assets/logo-short.png
  favicon: assets/logo.ico
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.instant
  palette:
    # Mode clair
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre

    # Mode sombre
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

# ==============================================================================
# Plugins
# ==============================================================================
plugins:
  - search
  - awesome-pages

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-links.js

# ==============================================================================
# Configurations Supplémentaires
# ==============================================================================
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enervision-project

# ==============================================================================
# Navigation
# ==============================================================================
nav:
  - Accueil: index.md
  - ...
  - Backend Java: 'https://votre-nom.github.io/repo-backend/'
  - Frontend Angular: 'https://votre-nom.github.io/repo-frontend/'
  - ML Python: 'https://votre-nom.github.io/repo-ml-python/'