[project]
name = "parent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bryan", email = "bryan.bruzois@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material>=9.7.7",
    "mkdocs-multirepo-plugin>=0.8.3",
]

[project.scripts]
parent-project = "parent_project:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
]
